<a href="https://colab.research.google.com/github/HimanshuVaidya25/project-1/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install imblearn

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

In [ ]:
data = pd.read_csv('/content/creditcard.csv')

In [ ]:
data

Time        V1        V2        V3        V4        V5        V6  \
0          0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...       ...       ...       ...       ...       ...   
43659  41598 -0.538686 -0.635328 -0.041569 -3.022158  0.771776  3.556774   
43660  41599 -0.349615 -2.860571  0.297766  0.801212 -1.523995  1.164260   
43661  41599 -3.001222  2.899766  0.726874 -0.729992 -0.312792 -0.735557   
43662  41599  1.042342 -0.390001 -0.463680 -1.737393  0.450611  0.604354   
43663  41600  1.193909  0.067328  0.609239  0.825453 -0.332038 -0.101522   

             V7        V8        V9  ...       V21       V22       V23  \
0      0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1     -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2      0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3      0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4      0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...         ...       ...       ...  ...       ...       ...       ...   
43659 -1.418820  1.371999 -2.475053  ... -0.090409 -0.310254  0.168510   
43660  0.037484  0.325220  0.862825  ...  0.315370 -0.503099 -0.514747   
43661  0.960944 -0.276141  2.128747  ... -0.645540 -0.613956  0.111663   
43662  0.068099  0.278030  0.555053  ... -0.137137 -0.286887  0.143336   
43663 -0.130782 -0.033697  0.424588  ... -0.049950  0.213908 -0.068750   

            V24       V25       V26       V27       V28  Amount  Class  
0      0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62    0.0  
1     -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69    0.0  
2     -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66    0.0  
3     -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50    0.0  
4      0.141267 -0.206010  0.502292  0.219422  0.215153   69.99    0.0  
...         ...       ...       ...       ...       ...     ...    ...  
43659  0.955413 -0.427495 -0.375891  0.051010  0.072416   60.01    0.0  
43660 -0.193890 -0.327091  0.875820 -0.144908  0.125368  745.56    0.0  
43661  0.338567  0.268357  0.076981  1.184716  0.491066    8.99    0.0  
43662 -0.986810  0.135599 -0.185344  0.035590 -0.008304   48.00    0.0  
43663  0.182281  0.557841  0.400000       NaN       NaN     NaN    NaN  

[43664 rows x 31 columns]

In [ ]:
X = data.drop('Class', axis=1)
X

Time        V1        V2        V3        V4        V5        V6  \
0          0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...       ...       ...       ...       ...       ...   
43659  41598 -0.538686 -0.635328 -0.041569 -3.022158  0.771776  3.556774   
43660  41599 -0.349615 -2.860571  0.297766  0.801212 -1.523995  1.164260   
43661  41599 -3.001222  2.899766  0.726874 -0.729992 -0.312792 -0.735557   
43662  41599  1.042342 -0.390001 -0.463680 -1.737393  0.450611  0.604354   
43663  41600  1.193909  0.067328  0.609239  0.825453 -0.332038 -0.101522   

             V7        V8        V9  ...       V20       V21       V22  \
0      0.239599  0.098698  0.363787  ...  0.251412 -0.018307  0.277838   
1     -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672   
2      0.791461  0.247676 -1.514654  ...  0.524980  0.247998  0.771679   
3      0.237609  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274   
4      0.592941 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278   
...         ...       ...       ...  ...       ...       ...       ...   
43659 -1.418820  1.371999 -2.475053  ... -0.103447 -0.090409 -0.310254   
43660  0.037484  0.325220  0.862825  ...  1.330992  0.315370 -0.503099   
43661  0.960944 -0.276141  2.128747  ...  1.737831 -0.645540 -0.613956   
43662  0.068099  0.278030  0.555053  ... -0.104876 -0.137137 -0.286887   
43663 -0.130782 -0.033697  0.424588  ... -0.086323 -0.049950  0.213908   

            V23       V24       V25       V26       V27       V28  Amount  
0     -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1      0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2      0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3     -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4     -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  
...         ...       ...       ...       ...       ...       ...     ...  
43659  0.168510  0.955413 -0.427495 -0.375891  0.051010  0.072416   60.01  
43660 -0.514747 -0.193890 -0.327091  0.875820 -0.144908  0.125368  745.56  
43661  0.111663  0.338567  0.268357  0.076981  1.184716  0.491066    8.99  
43662  0.143336 -0.986810  0.135599 -0.185344  0.035590 -0.008304   48.00  
43663 -0.068750  0.182281  0.557841  0.400000       NaN       NaN     NaN  

[43664 rows x 30 columns]

In [ ]:
y = data['Class']
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
43659    0.0
43660    0.0
43661    0.0
43662    0.0
43663    NaN
Name: Class, Length: 43664, dtype: float64

In [ ]:
y = data['Class'].dropna()
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
43658    0.0
43659    0.0
43660    0.0
43661    0.0
43662    0.0
Name: Class, Length: 43663, dtype: float64

In [ ]:
X = data.loc[y.index].drop('Class', axis=1)
X

Time        V1        V2        V3        V4        V5        V6  \
0          0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...       ...       ...       ...       ...       ...   
43658  41598 -0.319097  1.216372  0.770942  0.305980  0.718387 -0.371581   
43659  41598 -0.538686 -0.635328 -0.041569 -3.022158  0.771776  3.556774   
43660  41599 -0.349615 -2.860571  0.297766  0.801212 -1.523995  1.164260   
43661  41599 -3.001222  2.899766  0.726874 -0.729992 -0.312792 -0.735557   
43662  41599  1.042342 -0.390001 -0.463680 -1.737393  0.450611  0.604354   

             V7        V8        V9  ...       V20       V21       V22  \
0      0.239599  0.098698  0.363787  ...  0.251412 -0.018307  0.277838   
1     -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672   
2      0.791461  0.247676 -1.514654  ...  0.524980  0.247998  0.771679   
3      0.237609  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274   
4      0.592941 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278   
...         ...       ...       ...  ...       ...       ...       ...   
43658  1.219717 -0.299580 -0.808841  ...  0.014440  0.018979  0.102120   
43659 -1.418820  1.371999 -2.475053  ... -0.103447 -0.090409 -0.310254   
43660  0.037484  0.325220  0.862825  ...  1.330992  0.315370 -0.503099   
43661  0.960944 -0.276141  2.128747  ...  1.737831 -0.645540 -0.613956   
43662  0.068099  0.278030  0.555053  ... -0.104876 -0.137137 -0.286887   

            V23       V24       V25       V26       V27       V28  Amount  
0     -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1      0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2      0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3     -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4     -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  
...         ...       ...       ...       ...       ...       ...     ...  
43658 -0.318324 -0.424313  0.452073 -0.362634 -0.082331  0.004286   33.41  
43659  0.168510  0.955413 -0.427495 -0.375891  0.051010  0.072416   60.01  
43660 -0.514747 -0.193890 -0.327091  0.875820 -0.144908  0.125368  745.56  
43661  0.111663  0.338567  0.268357  0.076981  1.184716  0.491066    8.99  
43662  0.143336 -0.986810  0.135599 -0.185344  0.035590 -0.008304   48.00  

[43663 rows x 30 columns]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-2.09819285, -0.5987334 , -0.06467138, ...,  0.32447353,
        -0.07643196,  0.24872616],
       [-2.09819285,  0.75747107,  0.14531026, ..., -0.04060545,
         0.02809866, -0.36748957],
       [-2.09811481, -0.5979611 , -0.8498643 , ..., -0.15936809,
        -0.18949855,  1.20930638],
       ...,
       [ 1.14797634, -0.06181816, -1.79181689, ..., -0.38873808,
         0.35136718,  2.74806329],
       [ 1.14797634, -1.47114239,  1.77693832, ...,  3.01671149,
         1.41983022, -0.34106774],
       [ 1.14797634,  0.67800382, -0.26120183, ...,  0.07355693,
        -0.03918168, -0.17746211]])

In [ ]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_scaled, y)
X_resampled, y_resampled

(array([[ -2.09819285,  -0.5987334 ,  -0.06467138, ...,   0.32447353,
          -0.07643196,   0.24872616],
        [ -2.09819285,   0.75747107,   0.14531026, ...,  -0.04060545,
           0.02809866,  -0.36748957],
        [ -2.09811481,  -0.5979611 ,  -0.8498643 , ...,  -0.15936809,
          -0.18949855,   1.20930638],
        ...,
        [  1.12150327,  -5.81117977,   3.89693631, ...,  -0.98842982,
          -2.04925173,   0.26254962],
        [ -1.47904287,   0.42803744,   1.53255016, ...,   1.53794732,
           0.41768847,  -0.37457733],
        [ -0.01637563, -10.74923858,   7.62755524, ...,   4.02113777,
           1.35839118,   0.04058088]]),
 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ... 
 87053    1.0
 87054    1.0
 87055    1.0
 87056    1.0
 87057    1.0
 Name: Class, Length: 87058, dtype: float64)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

In [ ]:
X_train, X_test, y_train, y_test

(array([[-1.29615128,  0.7518762 ,  0.20070125, ..., -0.04920654,
          0.01177951, -0.36828642],
        [ 1.11877603, -4.63225729,  4.05654171, ...,  1.48771844,
         -1.15873642,  1.40422917],
        [-2.00720428, -0.6002533 ,  0.62125662, ..., -1.28281106,
          0.10692098, -0.29816373],
        ...,
        [ 0.78560869, -0.06372093,  0.92402928, ...,  1.37101083,
          0.55388291, -0.29936872],
        [-2.04715809, -0.31903852,  0.35596817, ...,  0.40342446,
          0.78668187, -0.33725126],
        [ 0.02708463,  0.65324599,  0.18436912, ..., -0.1864522 ,
          0.0300534 ,  0.09828951]]),
 array([[  0.84005107,  -0.25364498,   0.69903259, ...,   0.93697952,
           0.4873102 ,  -0.3679509 ],
        [  0.85308288,  -0.46260482,   0.78435663, ...,  -0.37343819,
           0.13731712,  -0.30156082],
        [  0.11584755, -14.6297748 ,   9.64123913, ...,   3.35961323,
           1.10519068,   0.04058088],
        ...,
        [  0.09505294,   0.77191593,

In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
model

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0., 0., 1., ..., 0., 1., 1.])

In [ ]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[8671    2]
 [   0 8739]]


In [ ]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8673
         1.0       1.00      1.00      1.00      8739

    accuracy                           1.00     17412
   macro avg       1.00      1.00      1.00     17412
weighted avg       1.00      1.00      1.00     17412



In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [ ]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
f1

0.9998855835240276

In [ ]:
precision

0.9997711932273196

In [ ]:
recall

1.0

In [ ]:
print("\nPrecision: ", precision)
print("Recall: ", recall)
print("F1-Score: ", f1)


Precision:  0.9997711932273196
Recall:  1.0
F1-Score:  0.9998855835240276
