<a href="https://colab.research.google.com/github/HimanshuVaidya25/project-1/blob/main/Movie_Rating_Prediction_With_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

**Load the dataset**

In [ ]:
!pip install pandas numpy scikit-learn

In [ ]:
data = pd.read_csv("/content/IMDb Movies India.csv", encoding='latin-1')

In [ ]:
data

Name    Year Duration            Genre  \
0                                             NaN      NaN            Drama   
1      #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama   
2                             #Homecoming  (2021)   90 min   Drama, Musical   
3                                 #Yaaram  (2019)  110 min  Comedy, Romance   
4                       ...And Once Again  (2010)  105 min            Drama   
...                                   ...     ...      ...              ...   
15504                 Zulm Ko Jala Doonga  (1988)      NaN           Action   
15505                               Zulmi  (1999)  129 min    Action, Drama   
15506                           Zulmi Raj  (2005)      NaN           Action   
15507                       Zulmi Shikari  (1988)      NaN           Action   
15508                        Zulm-O-Sitam  (1998)  130 min    Action, Drama   

       Rating Votes            Director           Actor 1             Actor 2  \
0         NaN   NaN       J.S. Randhawa          Manmauji              Birbal   
1         7.0     8       Gaurav Bakshi      Rasika Dugal      Vivek Ghamande   
2         NaN   NaN  Soumyajit Majumdar      Sayani Gupta   Plabita Borthakur   
3         4.4    35          Ovais Khan           Prateik          Ishita Raj   
4         NaN   NaN        Amol Palekar      Rajat Kapoor  Rituparna Sengupta   
...       ...   ...                 ...               ...                 ...   
15504     4.6    11       Mahendra Shah  Naseeruddin Shah       Sumeet Saigal   
15505     4.5   655          Kuku Kohli      Akshay Kumar      Twinkle Khanna   
15506     NaN   NaN          Kiran Thej   Sangeeta Tiwari                 NaN   
15507     NaN   NaN                 NaN               NaN                 NaN   
15508     6.2    20        K.C. Bokadia        Dharmendra          Jaya Prada   

               Actor 3  
0      Rajendra Bhatia  
1        Arvind Jangid  
2           Roy Angana  
3      Siddhant Kapoor  
4          Antara Mali  
...                ...  
15504    Suparna Anand  
15505      Aruna Irani  
15506              NaN  
15507              NaN  
15508      Arjun Sarja  

[15509 rows x 10 columns]

**Display the first few rows of the dataset**

In [ ]:
print(data.head())

                                 Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama   
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama   
2                         #Homecoming  (2021)   90 min   Drama, Musical   
3                             #Yaaram  (2019)  110 min  Comedy, Romance   
4                   ...And Once Again  (2010)  105 min            Drama   

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal   
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande   
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur   
3     4.4    35          Ovais Khan       Prateik          Ishita Raj   
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta   

           Actor 3  
0  Rajendra Bhatia  
1    Arvind Jangid  
2       Roy Angana  
3  Siddhant Kapoor  
4    

# **Data Preprocessing**

In [ ]:
features = ['Genre', 'Director', 'Actor 1']
target = 'Rating'

In [ ]:
print(data.columns)

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')


**Handle missing values**

In [ ]:
data.dropna(subset=features + [target], inplace=True)

In [ ]:
data

Name    Year Duration  \
1      #Gadhvi (He thought he was Gandhi)  (2019)  109 min   
3                                 #Yaaram  (2019)  110 min   
5                    ...Aur Pyaar Ho Gaya  (1997)  147 min   
6                               ...Yahaan  (2005)  142 min   
8                      ?: A Question Mark  (2012)   82 min   
...                                   ...     ...      ...   
15501                     Zulm Ki Hukumat  (1992)      NaN   
15503                     Zulm Ki Zanjeer  (1989)  125 min   
15504                 Zulm Ko Jala Doonga  (1988)      NaN   
15505                               Zulmi  (1999)  129 min   
15508                        Zulm-O-Sitam  (1998)  130 min   

                           Genre  Rating  Votes           Director  \
1                          Drama     7.0      8      Gaurav Bakshi   
3                Comedy, Romance     4.4     35         Ovais Khan   
5         Comedy, Drama, Musical     4.7    827       Rahul Rawail   
6            Drama, Romance, War     7.4  1,086     Shoojit Sircar   
8      Horror, Mystery, Thriller     5.6    326      Allyson Patel   
...                          ...     ...    ...                ...   
15501       Action, Crime, Drama     5.3    135  Bharat Rangachary   
15503       Action, Crime, Drama     5.8     44    S.P. Muthuraman   
15504                     Action     4.6     11      Mahendra Shah   
15505              Action, Drama     4.5    655         Kuku Kohli   
15508              Action, Drama     6.2     20       K.C. Bokadia   

                Actor 1                 Actor 2          Actor 3  
1          Rasika Dugal          Vivek Ghamande    Arvind Jangid  
3               Prateik              Ishita Raj  Siddhant Kapoor  
5            Bobby Deol  Aishwarya Rai Bachchan    Shammi Kapoor  
6       Jimmy Sheirgill          Minissha Lamba   Yashpal Sharma  
8             Yash Dave          Muntazir Ahmad     Kiran Bhatia  
...                 ...                     ...              ...  
15501        Dharmendra     Moushumi Chatterjee          Govinda  
15503       Chiranjeevi              Jayamalini      Rajinikanth  
15504  Naseeruddin Shah           Sumeet Saigal    Suparna Anand  
15505      Akshay Kumar          Twinkle Khanna      Aruna Irani  
15508        Dharmendra              Jaya Prada      Arjun Sarja  

[7707 rows x 10 columns]

**Convert categorical features to numerical**

**Using OneHotEncoder for 'Genre' and 'Director'**

In [ ]:
onehot = OneHotEncoder()
genre_encoded = onehot.fit_transform(data[['Genre']]).toarray()

In [ ]:
genre_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
director_encoded = onehot.fit_transform(data[['Director']]).toarray()
director_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
vectorizer = CountVectorizer()
actors_encoded = vectorizer.fit_transform(data['Actor 1']).toarray()

In [ ]:
X = np.hstack((genre_encoded, director_encoded, actors_encoded))
y = data[target].values
X
y

array([7. , 4.4, 4.7, ..., 4.6, 4.5, 6.2])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([ 4.91406250e+00,  9.84979281e+12,  6.94921875e+00, ...,
       -2.40531215e+11, -5.85871742e+12,  2.50992004e+12])

**Evaluate the Model**

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mse

1.0033628089387343e+26

In [ ]:
r2 = r2_score(y_test, y_pred)
r2

-5.199120834863808e+25

In [ ]:
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")

Mean Squared Error: 1.0033628089387343e+26
R^2 Score: -5.199120834863808e+25


**Displaying first few predictions**

In [ ]:
print(f"Predicted Ratings: {y_pred[:5]}")
print(f"Actual Ratings: {y_test[:5]}")

Predicted Ratings: [ 4.91406250e+00  9.84979281e+12  6.94921875e+00  6.37695312e+00
 -1.69883904e+13]
Actual Ratings: [3.  6.9 6.2 8.  9.3]
